spring:
  application:
    name: kuzushiji
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 466899164217-o1dnr5imc1knsirdfahea277v85a5pvc.apps.googleusercontent.com
            clientSecret: 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
tensorFlowServerHost:  http://127.0.0.1:5000/file-upload
