spring:
  application:
    name: kuzushiji
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs
tensorFlowServerHost:  http://127.0.0.1:5000/file-upload
server:
  port:
    8082

